language: c
before_install:
- echo "deb http://fr.archive.ubuntu.com/ubuntu/ trusty universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- ulimit -c unlimited -S
- sudo apt-get install gdb
- sudo apt-get install mininet/precise-backports
# prerequisites for tox:
- sudo add-apt-repository -y ppa:fkrull/deadsnakes
- sudo apt-get update
- sudo apt-get install python2.6 python2.7 python3.3 python3.4 python
- sudo pip install tox
install:
- sed -i 's/_mt/_st/' build.py
- sudo apt-get install python-coverage libfuse-dev librdkafka-dev libjansson-dev libzookeeper-st-dev
- sudo pip install fabricate cpp-coveralls
script:
- ./build.py test_all
after_failure:
- find
- cat /proc/sys/kernel/core_pattern
- dmesg
- sudo cat /var/log/messages
- gdb --batch --quiet -ex "thread apply all bt full" -ex "quit" fuse_kafka.test core*
after_success:
- coveralls --exclude bin --exclude tests --gcov-options '\-lp'
- git config --global user.name "${GIT_NAME}"
- git config --global user.email "${GIT_EMAIL}"
- mkdir doc
- cd doc
- git clone https://github.com/yazgoo/fuse_kafka.git .
- git checkout gh-pages
- cd ..
- sudo apt-get install doxygen
- ./build.py doc
- cd doc
- git add --all .
- git commit -m "auto updating documenation"
- git push https://${GH_TOKEN}@github.com/yazgoo/fuse_kafka.git gh-pages
env:
  global:
    secure: LZlIH/SfgTMAQjUULjIk4j6pxhxVKPRvzRopdDeFnXrRozIeBdUUOePQEMoFYiiu/qAhoROEiO9SupvyX6YE2wGpEm/PIN30HmAXN1OxabpADPjyjbCHycaYb8ejl9xjoA3w68YbT7ezhV/ut1fvuihDZxotqUodXK7n1m7M+K4=
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d3c4bddd8542f4a29b44
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
